login/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('',views.check_user,name='check_user'),
    path('',views.logout_view,name='logout_view')
]

psixologik_test/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('adminsite111/', admin.site.urls),
    path('',include('psixolog.urls')),
    path('login/',include('login.urls')),
    path('question/',include('questions.urls')),
    path('quiz/',include('quiz.urls',namespace='quiz')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'Psixologiya adminstratsiyasi'
admin.site.index_title = 'Funksiyalar'

quiz/urls.py
from django.urls import path
from . import views

app_name = 'quiz'

urlpatterns = [
    path('',views.QuizListView.as_view(),name='main-view'),
    path('<pk>/',views.quiz_view,name='quiz-view'),
    path('<pk>/data/',views.quiz_data_view,name='quiz_data_view'),
    path('<pk>/save/',views.save_quiz_view,name='save-view'),
]

login/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

class Login(models.Model):
    username = models.CharField(max_length=100,null=False)
    password = models.CharField(max_length=100,null=False)

    class Meta:
        verbose_name = _('Login')

quiz/models.py
from django.db import models
from questions import *
import random
class Quiz(models.Model):
    name = models.CharField(max_length=200)
    topic = models.CharField(max_length=200)
    number_of_questions = models.IntegerField()
    time = models.IntegerField(help_text='Testni vaqtini kiriting: ')
    required_score_to_pass = models.IntegerField(help_text='natija')

    def __str__(self):
        return f"{self.name}-{self.topic}"

    def get_questions(self):
        questions = list(self.question_set.all())
        random.shuffle(questions)
        return questions[:self.number_of_questions]

    class Meta:
        verbose_name = 'Ro\'yxat'
        verbose_name_plural = 'Savollar ro\'yxati'

login/forms.py
from django import forms
from .models import Login



class LoginForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={'class':'form-control',
                   'placeholder':'Username'}
        ),
        max_length=150
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'placeholder':'parol'})
    )

login/views.py
from django.contrib import messages
from django.shortcuts import render,HttpResponse,redirect
from django.contrib.auth.models import User
from .forms import LoginForm
from django.contrib.auth import authenticate, login,logout
from django.contrib import admin
a = []
def check_user(request):
    users = User.objects.filter(is_staff=True)
    for u in users:
        a.append(u.username)
    form = LoginForm()
    username = request.POST.get('username')
    password = request.POST.get('password')
    user = authenticate(request, username=username, password=password)
    if user is not None:
       login(request, user)
       if username in a:
           return redirect('/adminsite111')
       else:
            return redirect('/quiz')
    return render(request,'login_page.html',{'form':form})

def logout_view(request):
    logout(request)
    return check_user(request)

# def admin(request):
#     user = users.objects.get(category = 'admin')
#     if user:
#         return render(request, 'main/admin.html')
#
#     elif Exception:
#         return render(request, 'main/home.html')

quiz/views.py
from django.shortcuts import render
from .models import Quiz
from django.views.generic import ListView
from django.http import JsonResponse
from questions.models import Question,Answer
from results.models import Result
class QuizListView(ListView):
    model = Quiz
    template_name = 'main.html'

def quiz_view(request,pk):
    quiz = Quiz.objects.get(pk=pk)
    return render(request,'quiz.html',{'obj':quiz})
def quiz_data_view(request,pk):
    quiz = Quiz.objects.get(pk=pk)
    questions = []
    for q in quiz.get_questions():
        answers = []
        for a in q.get_answers():
            answers.append(a.text)
        questions.append({str(q):answers})
    return JsonResponse(
        {
            'data':questions,
            'time':quiz.time,
        }
    )

def save_quiz_view(request,pk):

    if request.is_ajax():
        questions = []
        data = request.POST
        data1 = dict(data.lists())
        data1.pop('csrfmiddlewaretoken')
        for k in data1.keys():
            question = Question.objects.get(text=k)
            questions.append(question)
        user = request.user
        user_data = user.first_name+" "+user.last_name
        quiz = Quiz.objects.get(pk=pk)
        score = 0
        multiplier = 100/quiz.number_of_questions
        results = []
        correct_answer = None
        for que in questions:
            a_selected = request.POST.get(que.text)
            if a_selected != "":
                question_answers = Answer.objects.filter(question=que)
                for a in question_answers:
                    if a_selected == a.text:
                        if a.correct:
                            score+=1
                            correct_answer = a.text
                    else:
                        if a.correct:
                            correct_answer = a.text
                results.append({str(que):{'correct_answer':correct_answer,'answered':a_selected}})
            else:
                results.append({str(que):'not answered'})
        score_ = score*multiplier
        Result.objects.create(quiz=quiz,user=user,score=score_)
        if score_>quiz.required_score_to_pass:
            return JsonResponse({'passed':True,'natija':score_,'results':results,'pol':user_data})
        else:
            return JsonResponse({'passed':False,'natija':score_,'results':results,'pol':user_data})

templates/add_user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form action="" method="post">
        {% csrf_token %}
        <table>{{form}}</table>

        <input type="submit" value="Send">
    </form>
</body>
</html>

templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static '/main.css' %}">
    <link rel="stylesheet" href="{% static '/style.css' %}">


    <title>My Website</title>
</head>

<body>
<div class="loader">
    <div class="lds-roller">
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
    </div>
</div>

<div class="sdfs">

    <!-- Header -->
    <section id="header">
        <div class="header container">
            <div class="nav-bar">
                <div class="brand">
                    <a href="#hero">
                        <h1><span>Psi</span>xa <span>lo</span>giya</h1>
                    </a>
                </div>
                <div class="nav-list">
                    <div class="hamburger">
                        <div class="bar"></div>
                    </div>
                    <ul>
                        <li><a href="#hero" data-after="Home">Asosiy</a></li>
                        <li><a href="#projects" data-after="Projects">Maqollalar</a></li>
                        <li><a href="#about" data-after="About">Biz haqimizda</a></li>
                        <li><a href="#contact" data-after="Contact">Biz bilan bog`lanish</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </section>
    <!-- End Header -->


    <!-- Hero Section  -->
    <section id="hero">
        <div class="hero container">
            <div>
                <h1>Xush kelibsiz <span></span></h1>
                <h1>Psixalogik test <span></span></h1>
                <h1>topshirishga <span></span></h1>
                <a href="{%url  'check_user'%}" type="button" class="cta">Test topshirish</a>
            </div>

        </div>
    </section>
    <!-- End Hero Section  -->

    <!-- Projects Section -->
    <section id="projects">
        <div class="projects container">
            <div class="projects-header">
                <h1 class="section-title">Eng so`ngi <span>Maqolalar</span></h1>
            </div>
            <div class="all-projects">
                {% for pro in proekt %}
                <div class="project-item">
                    <div class="project-info">
                        <h1>{{pro.name}}</h1>
                        <h2>{{pro.description}}</h2>
                        <a href="{% url 'read' %}" type="button" class="cta">Maqolani o'qish</a>
                         <a href="{{pro.file.url}}" download="{{pro.file.url}}" class="cta">Yuklab olish</a>
                    </div>
                    <div class="project-img">
                        <img src="{{pro.image.url}}" alt="img">
                    </div>
                </div>
                {% endfor %}

            </div>
        </div>
    </section>
    <!-- End Projects Section -->

    <!-- About Section -->

    <section id="about">
        {% for a in data %}
        <div class="about container">
            <div class="col-left">
                <div class="about-img">
                    <img src="{{a.image.url}}" alt="img">
                </div>
            </div>
            <div class="col-right">
                <h1 class="section-title">About <span>me</span></h1>
                <h2>{{a.specialist}}</h2>
                <p>{{a.info}}</p>
                <a href="{{a.resume.url}}" download="{{a.resume.url}}" class="cta">Download Resume</a>
            </div>
        </div>
        {% endfor %}
    </section>

    <!-- End About Section -->

    <!-- Contact Section -->
    <section id="contact">
        <div class="contact container">
            <div>
                <h1 class="section-title">Contact <span>info</span></h1>
            </div>
            <div class="contact-items">
                <div class="contact-item">
                    <div class="icon"><img src="https://img.icons8.com/bubbles/100/000000/phone.png"/></div>
                    <div class="contact-info">
                        <h1>Phone</h1>
                        <h2>+1 234 123 1234</h2>
                        <h2>+1 234 123 1234</h2>
                    </div>
                </div>
                <div class="contact-item">
                    <div class="icon"><img src="https://img.icons8.com/bubbles/100/000000/new-post.png"/></div>
                    <div class="contact-info">
                        <h1>Email</h1>
                        <h2>info@gmail.com</h2>
                        <h2>abcd@gmail.com</h2>
                    </div>
                </div>
                <div class="contact-item">
                    <div class="icon"><img src="https://img.icons8.com/bubbles/100/000000/map-marker.png"/></div>
                    <div class="contact-info">
                        <h1>Address</h1>
                        <h2>Fatikchhari, Chittagong, Bangladesh</h2>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- End Contact Section -->

    <!-- Footer -->
    <section id="footer">
        <div class="footer container">
            <div class="brand">
                <h1><span>Psi</span>ha <span>lo</span>giya</h1>
            </div>
            <h2>Your Complete Web Solution</h2>
            <div class="social-icon">
                <div class="social-item">
                    <a href="#"><img src="https://img.icons8.com/bubbles/100/000000/facebook-new.png"/></a>
                </div>
                <div class="social-item">
                    <a href="#"><img src="https://img.icons8.com/bubbles/100/000000/instagram-new.png"/></a>
                </div>
                <div class="social-item">
                    <a href="#"><img src="https://img.icons8.com/bubbles/100/000000/twitter.png"/></a>
                </div>
                <div class="social-item">
                    <a href="#"><img src="https://img.icons8.com/bubbles/100/000000/behance.png"/></a>
                </div>
            </div>
            <p>Copyright © 2020 Arfan. All rights reserved</p>
        </div>
    </section>
    <!-- End Footer -->
</div>

<script type="text/javascript" src="{% static 'app.js' %}"></script>
<script type="text/javascript" src="{% static 'main.js' %}"></script>


</body>

</html>

templates/index1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
    <li><a href="{% url 'detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}

    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
 <form method="POST">
    {% csrf_token %}
    <table>
        {{form}}
    </table>
    <input type="submit" value="send">

</form>

</body>
</html>

templates/login_page.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title>Document</title>
</head>
      <link rel="stylesheet" href="{% static '/login_style.css' %}">
<body>
		<div class="wrapper fadeInDown">
  <div id="formContent">
    <!-- Tabs Titles -->
    <h2 class="active"> Sign In </h2>

    <!-- Icon -->
<!--     <div class="fadeIn first">
      <img src="http://danielzawadzki.com/codepen/01/icon.svg" id="icon" alt="User Icon" />
    </div> -->

    <!-- Login Form -->
    <form method="POST" >
        {% csrf_token %}
        <input type="text" id="login" class="fadeIn second" name="username" placeholder="username">
        <input type="text" id="password" class="fadeIn third" name="password" placeholder="password">
        <input type="submit" class="fadeIn fourth" value="Kirish">
    </form>

    <!-- Remind Passowrd -->
    <div id="formFooter">
        <a href="{% url 'register' %}">Ro'yhatdan o'tish</a>
    </div>

  </div>
</div>
</body>
</html>

templates/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
      <link rel="stylesheet" href="{% static '/startTest.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
<!-- Button trigger modal -->

<!-- Modal -->
<div class="modal fade" id="quizStartModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Boshlaysizmi?</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" id="modal-body-confirm">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Yo'q</button>
                <button type="button" class="btn btn-success" id="start-button">Boshlash</button>
            </div>
        </div>
    </div>
</div>
<div class="text-center  startTest px-5">
    <h1 class="py-5 ">Testlar Ro'yxati</h1>

    <div class="row">
         {% for obj in object_list %}
        <div class="col-md-4 col-sm-6 py-3">
            <button
                    class="btn  modal-button btn-success simple py-5 w-100"
                    data-pk="{{obj.pk}}"
                    data-name="{{obj.name}}"
                    data-questions="{{obj.number_of_questions}}"
                    data-time="{{obj.time}}"
                    data-pass="{{obj.required_score_to_pass}}"
                    data-bs-toggle="modal"
                    data-bs-target="#quizStartModal">
                {{obj.name}}
            </button>
        </div>
         {% endfor %}

    </div>

</div>


</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
<script type="text/javascript" src="{% static 'main-quiz.js' %}"></script>
</html>

templates/quiz.html
<!DOCTYPE html>
{% load static %}
<html lang="en" xmlns="http://www.w3.org/1999/html">

<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel="stylesheet" href="{% static '/quizStyle.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.9.2/html2pdf.bundle.js"></script>
<body>


<div class="row  text-center d-flex">
    <div class="col-4"></div>
    <div class="col-md-3 "><h2>{{obj.name}}</h2></div>
    <div class="col-md-1" id="time-box"></div>
</div>
<form id="quiz-form" class="mt-3 mb-3">
    {% csrf_token %}
    <div id="quiz-box"></div>
    <div class="text-center">

        <button type="submit" class="btn btn-success  w-25 ml-5" id="btn">Saqlash</button>
    </div>

</form>
<div id="score-box"></div>
<div id="result-box"></div>
<div id="show" class="text-center py-3">
    <button id="cmd" type="button" class="btn btn-primary w-25 p-3">yuklab olish</button>
    <a id="back" href="{% url 'quiz:main-view' %}" class="btn btn-danger ml-2 w-25 p-3">Orqaga</a>
</div>
</body>
<script type="text/javascript" src="{% static 'quiz.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js" integrity="sha512-GsLlZN/3F2ErC5ifS5QtgpiJtWd43JWSuIgh7mbzZ8zBps+dvLusV+eNQATqgA/HdeKFVgA5v3S/cIrLF7QnIg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script type="text/javascript" src="{% static 'result.js' %}"></script>
<script type="text/javascript" src="{% static 'result.js' %}"></script>
</html>

templates/read_article.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>
<div class="container">
  <div class="row">
    {% for a in art %}
        <p class="text-justify">{{a.text}}</p>
    {% endfor %}
    </div>
  </div>
</body>
</html>

templates/reg1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
        <div class="modal fade" id="quizStartModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Bunday nom bilan foydalanuvchi mavjud!</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body" id="modal-body-confirm">
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Yo'q</button>
                        <button type="button" class="btn btn-success" id="start-button">Boshlash</button>
                    </div>
                </div>
            </div>
        </div>
    <h1>salom dunya</h1>
</body>
</html>

templates/register.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title>Document</title>
</head>
    <link rel="stylesheet" href="{% static '/login_style.css' %}">
<body>
		<div class="wrapper fadeInDown">
  <div id="formContent">
    <!-- Tabs Titles -->
    <h2 class="active">Registration</h2>


    <!-- Icon -->
<!--     <div class="fadeIn first">
      <img src="http://danielzawadzki.com/codepen/01/icon.svg" id="icon" alt="User Icon" />
    </div> -->

    <!-- Login Form -->
    <form method="POST">
      {% csrf_token %}
      <input type="text" id="login" class="fadeIn second" name="username" placeholder="Foydalanuvchi nomi">
      <input type="text" id="first_name" class="fadeIn second" name="first_name" placeholder="Ismingiz">
      <input type="text" id="last_name" class="fadeIn second" name="last_name" placeholder="Familiyangiz">
      <input type="text" id="email" class="fadeIn third" name="email" placeholder="Elektron Pochta">
      <input type="text" id="password" class="fadeIn third " name="password" placeholder="Parol">
      <input type="submit" class="fadeIn fourth" value="Ro'yhatdan o'tish">
    </form>

    <!-- Remind Passowrd -->
    <div id="formFooter">

    </div>

  </div>
</div>
{% if alr %}
  <h1>salom</h1>
{% endif %}
</body>
</html>

templates/user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Hello {{user.first_name}}!</h1>

    <a href="{% url 'logout_view' %}">Logout</a>

</body>
</html>